/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/Exam': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'text/plain': components['schemas']['Exam'][];
                        'application/json': components['schemas']['Exam'][];
                        'text/json': components['schemas']['Exam'][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    'application/json': components['schemas']['ExamCreateDTO'];
                    'text/json': components['schemas']['ExamCreateDTO'];
                    'application/*+json': components['schemas']['ExamCreateDTO'];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'text/plain': components['schemas']['Exam'];
                        'application/json': components['schemas']['Exam'];
                        'text/json': components['schemas']['Exam'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/Lesson': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'text/plain': components['schemas']['Lesson'][];
                        'application/json': components['schemas']['Lesson'][];
                        'text/json': components['schemas']['Lesson'][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    'application/json': components['schemas']['LessonCreateDTO'];
                    'text/json': components['schemas']['LessonCreateDTO'];
                    'application/*+json': components['schemas']['LessonCreateDTO'];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'text/plain': components['schemas']['Lesson'];
                        'application/json': components['schemas']['Lesson'];
                        'text/json': components['schemas']['Lesson'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/Student': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'text/plain': components['schemas']['Student'][];
                        'application/json': components['schemas']['Student'][];
                        'text/json': components['schemas']['Student'][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    'application/json': components['schemas']['StudentCreateDTO'];
                    'text/json': components['schemas']['StudentCreateDTO'];
                    'application/*+json': components['schemas']['StudentCreateDTO'];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'text/plain': components['schemas']['Student'];
                        'application/json': components['schemas']['Student'];
                        'text/json': components['schemas']['Student'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Exam: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            date?: string;
            /** Format: uuid */
            studentId?: string;
            /** Format: uuid */
            lessonId?: string;
            /** Format: int32 */
            grade?: number;
            /** Format: date-time */
            createdDate?: string;
            deletted?: boolean;
            student?: components['schemas']['Student'];
            lesson?: components['schemas']['Lesson'];
        };
        ExamCreateDTO: {
            /** Format: date-time */
            date: string;
            /** Format: uuid */
            studentId: string;
            /** Format: uuid */
            lessonId: string;
            /** Format: int32 */
            grade: number;
        };
        Lesson: {
            /** Format: uuid */
            id?: string;
            code?: string | null;
            name?: string | null;
            /** Format: int32 */
            class?: number;
            teacherName?: string | null;
            teacherSurname?: string | null;
            /** Format: date-time */
            createdDate?: string;
            deletted?: boolean;
        };
        LessonCreateDTO: {
            code: string | null;
            name: string | null;
            /** Format: int32 */
            class: number;
            teacherName: string | null;
            teacherSurname: string | null;
        };
        Student: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            studentNumber?: number;
            name?: string | null;
            surname?: string | null;
            /** Format: int32 */
            class?: number;
            /** Format: date-time */
            createdDate?: string;
            deletted?: boolean;
        };
        StudentCreateDTO: {
            /** Format: int32 */
            studentNumber: number;
            name: string | null;
            surname: string | null;
            /** Format: int32 */
            class: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
